### ISSUE TITLE
License issue with included MICOM code 

### ISSUE THREAD

**Issue by cdiener** [korem-lab/pymgpipe#3]
Hi,

Since you copied some of the MICOM source code into your software I just wanted to point out that MICOM's Apache 2.0 license [is not compatible](https://opensource.stackexchange.com/questions/12477/is-cc-by-sa-3-0-compatible-with-apache-2-0) with the CC-BY license you applied to your project. So you would need to transfer your project to a compatible license if you want to use MICOM source code in your codebase. Thanks!

**Comment by talkorem** [comment]
Hi @cdiener, thanks for pointing this oversight to us. We'll switch to a compatible license.
