### ISSUE TITLE
JOSS Review - General Comments

### ISSUE THREAD

**Issue by ammaraziz** [korem-lab/pymgpipe#5]
Hi there,

I had a few comments that I think could improve the user experience. Making these changes are not contingent on publishing.

-  Create a dedicated section in the readme with the full install instructions. The install instructions a bit light, while it is current enough to install the package, more detailed instructions would be beneficial. I suggest a full step by step instructions, including the how to use the suggested `pyenv`. I also suggest not including the local installation example as it can be confusing for beginners.
- Specify what version(s) of Python is recommended.
- Update the version in `setup.py` here https://github.com/korem-lab/pymgpipe/blob/main/setup.py#L5
- Add more information on how to generate/find taxa models 

Well done on creating this great tool and publishing.

Regards,

Ammar

**Comment by ym2877** [comment]
Hi Ammar!

Thank you so much for taking the time to review our package and for your thoughtful comments! I have just pushed some changes addressing your points- thank you for raising them. If you have any further questions/comments/concerns please don't hesitate to reach out :)

Best,
Yoli
